FROM node:22.13 AS deploy

ARG LIB_GIT_SOURCE
ARG LIB_PROJECT_NAME
ARG PROJECT_NAME

WORKDIR /usr/src/app/$PROJECT_NAME

COPY ./package*.json ./
COPY . ./

RUN npm install
RUN npm i $LIB_GIT_SOURCE#development

# temp
WORKDIR /usr/src/app/node_modoles/$LIB_PROJECT_NAME
RUN npm run prepare
WORKDIR /usr/src/app/$PROJECT_NAME

RUN npm run build:development
RUN npx cap sync web

EXPOSE 4174
CMD [ "npm", "run", "host:development" ]