FROM node:22.13 AS deploy

ARG LIB_GIT_SOURCE
ARG LIB_PROJECT_NAME
ARG PROJECT_NAME

# Build UI library
RUN git clone $LIB_GIT_SOURCE /usr/src/app/$LIB_PROJECT_NAME \
  && cd /usr/src/app/$LIB_PROJECT_NAME \
  && git checkout development \
  && npm i \
  && npm run build:library

# Build app
WORKDIR /usr/src/app/$PROJECT_NAME
COPY . .
RUN npm i /usr/src/app/$LIB_PROJECT_NAME \
  && npm run build:development \
  && npx cap sync web

EXPOSE 4174
CMD ["npm", "run", "host:development"]