FROM node:22.13 AS deploy

# Plug in the web repository
RUN git clone -b development https://github.com/ivanmatcuka/habbit-frontend.git /usr/src/app/habbit-frontend
WORKDIR /usr/src/app/habbit-frontend
RUN npm i

WORKDIR /usr/src/app/habbit-hybrid

COPY ./package*.json ./
COPY . ./

RUN npm install
RUN npm i github:ivanmatcuka/habits-frontend#development
RUN npm run build:development
RUN npx cap sync web

EXPOSE 4174
CMD [ "npm", "run", "host:development" ]